var searchData=
[
  ['name_0',['name',['../timer0_8cpp.html#autotoc_md20',1,'&amp;ndash;  Revised by:  Student&apos;s name'],['../main_8cpp.html#autotoc_md2',1,'&amp;ndash;  Revised by:  Student&apos;s name'],['../_monitor_8cpp.html#autotoc_md8',1,'&amp;ndash;  Revised by:  Student&apos;s name'],['../shared_8h.html#autotoc_md14',1,'&amp;ndash;  Revised by:  Student&apos;s name'],['../_u_a_r_t__poll_8cpp.html#autotoc_md25',1,'&amp;ndash;  Revised by:  Student&apos;s name']]],
  ['ndash_20copyright_20c_202015_202016_202022_20tim_20scherr_20all_20rights_20reserved_1',['&amp;ndash;      Copyright (c) 2015, 2016, 2022 Tim Scherr  All rights reserved.',['../main_8cpp.html#autotoc_md5',1,'']]],
  ['ndash_20copyright_20c_202015_202022_20tim_20scherr_20all_20rights_20reserved_2',['ndash copyright c 2015 2022 tim scherr all rights reserved',['../_u_a_r_t__poll_8cpp.html#autotoc_md28',1,'&amp;ndash;      Copyright (c) 2015, 2022 Tim Scherr  All rights reserved.'],['../shared_8h.html#autotoc_md17',1,'&amp;ndash;      Copyright (c) 2015, 2022 Tim Scherr  All rights reserved.'],['../_monitor_8cpp.html#autotoc_md11',1,'&amp;ndash;      Copyright (c) 2015, 2022 Tim Scherr All rights reserved.']]],
  ['ndash_20designed_20for_3a_20university_20of_20colorado_20at_20boulder_3',['ndash designed for: university of colorado at boulder',['../timer0_8cpp.html#autotoc_md19',1,'&amp;ndash;  Designed for:  University of Colorado at Boulder'],['../main_8cpp.html#autotoc_md1',1,'&amp;ndash;  Designed for:  University of Colorado at Boulder'],['../_monitor_8cpp.html#autotoc_md7',1,'&amp;ndash;  Designed for:  University of Colorado at Boulder'],['../shared_8h.html#autotoc_md13',1,'&amp;ndash;  Designed for:  University of Colorado at Boulder'],['../_u_a_r_t__poll_8cpp.html#autotoc_md24',1,'&amp;ndash;  Designed for:  University of Colorado at Boulder']]],
  ['ndash_20functional_20description_3a_20header_20file_20for_20all_20globals_4',['&amp;ndash; Functional Description:  Header file for all globals',['../shared_8h.html#autotoc_md16',1,'']]],
  ['ndash_20modified_20to_20implement_20a_20super_20loop_20bare_20metal_20os_5',['&amp;ndash;                           modified to implement a super loop bare metal OS.',['../main_8cpp.html#autotoc_md4',1,'']]],
  ['ndash_20ndash_6',['ndash ndash',['../main_8cpp.html#autotoc_md0',1,'&amp;ndash;                                                                           &amp;ndash;'],['../shared_8h.html#autotoc_md12',1,'&amp;ndash;                                                                           &amp;ndash;'],['../timer0_8cpp.html#autotoc_md18',1,'&amp;ndash;                                                                           &amp;ndash;'],['../_monitor_8cpp.html#autotoc_md6',1,'&amp;ndash;                                                                           &amp;ndash;'],['../_u_a_r_t__poll_8cpp.html#autotoc_md23',1,'&amp;ndash;                                                                           &amp;ndash;']]],
  ['ndash_20revised_20by_3a_20student_20s_20name_7',['ndash revised by: student s name',['../timer0_8cpp.html#autotoc_md20',1,'&amp;ndash;  Revised by:  Student&apos;s name'],['../main_8cpp.html#autotoc_md2',1,'&amp;ndash;  Revised by:  Student&apos;s name'],['../_monitor_8cpp.html#autotoc_md8',1,'&amp;ndash;  Revised by:  Student&apos;s name'],['../_u_a_r_t__poll_8cpp.html#autotoc_md25',1,'&amp;ndash;  Revised by:  Student&apos;s name'],['../shared_8h.html#autotoc_md14',1,'&amp;ndash;  Revised by:  Student&apos;s name']]],
  ['ndash_20st_20nucleo_20stm32f401re_20board_8',['ndash st nucleo stm32f401re board',['../main_8cpp.html#autotoc_md3',1,'&amp;ndash;              ST Nucleo STM32F401RE Board'],['../timer0_8cpp.html#autotoc_md21',1,'&amp;ndash;              ST Nucleo STM32F401RE Board'],['../shared_8h.html#autotoc_md15',1,'&amp;ndash;              ST Nucleo STM32F401RE Board'],['../_monitor_8cpp.html#autotoc_md9',1,'&amp;ndash;              ST Nucleo STM32F401RE Board'],['../_u_a_r_t__poll_8cpp.html#autotoc_md26',1,'&amp;ndash;              ST Nucleo STM32F401RE Board']]],
  ['ndash_20uart_5fhex_5fput_20a_20routine_20that_20puts_20a_20hex_20byte_20in_20the_20transmit_20buffer_9',['&amp;ndash;       UART_hex_put() - a routine that puts a hex byte in the transmit buffer',['../_u_a_r_t__poll_8cpp.html#autotoc_md27',1,'']]],
  ['nhd_5f0216hz_2ecpp_10',['NHD_0216HZ.cpp',['../_n_h_d__0216_h_z_8cpp.html',1,'']]],
  ['no_11',['NO',['../shared_8h.html#a996bde01ecac342918f0a2c4e7ce7bd5',1,'shared.h']]],
  ['normal_12',['NORMAL',['../shared_8h.html#ad8667bac763ba2aa5d7c29541fecf0a6a50d1448013c6f17125caee18aa418af7',1,'shared.h']]],
  ['nucleo_20stm32f401re_20board_13',['nucleo stm32f401re board',['../_monitor_8cpp.html#autotoc_md9',1,'&amp;ndash;              ST Nucleo STM32F401RE Board'],['../timer0_8cpp.html#autotoc_md21',1,'&amp;ndash;              ST Nucleo STM32F401RE Board'],['../shared_8h.html#autotoc_md15',1,'&amp;ndash;              ST Nucleo STM32F401RE Board'],['../main_8cpp.html#autotoc_md3',1,'&amp;ndash;              ST Nucleo STM32F401RE Board'],['../_u_a_r_t__poll_8cpp.html#autotoc_md26',1,'&amp;ndash;              ST Nucleo STM32F401RE Board']]]
];
