var group___a_d_c___exported___constants =
[
    [ "ADC_Common_mode", "group___a_d_c___common__mode.html", "group___a_d_c___common__mode" ],
    [ "ADC_Prescaler", "group___a_d_c___prescaler.html", "group___a_d_c___prescaler" ],
    [ "ADC_Direct_memory_access_mode_for_multi_mode", "group___a_d_c___direct__memory__access__mode__for__multi__mode.html", "group___a_d_c___direct__memory__access__mode__for__multi__mode" ],
    [ "ADC_delay_between_2_sampling_phases", "group___a_d_c__delay__between__2__sampling__phases.html", "group___a_d_c__delay__between__2__sampling__phases" ],
    [ "ADC_resolution", "group___a_d_c__resolution.html", "group___a_d_c__resolution" ],
    [ "ADC_external_trigger_edge_for_regular_channels_conversion", "group___a_d_c__external__trigger__edge__for__regular__channels__conversion.html", "group___a_d_c__external__trigger__edge__for__regular__channels__conversion" ],
    [ "ADC_extrenal_trigger_sources_for_regular_channels_conversion", "group___a_d_c__extrenal__trigger__sources__for__regular__channels__conversion.html", "group___a_d_c__extrenal__trigger__sources__for__regular__channels__conversion" ],
    [ "ADC_data_align", "group___a_d_c__data__align.html", "group___a_d_c__data__align" ],
    [ "ADC_channels", "group___a_d_c__channels.html", "group___a_d_c__channels" ],
    [ "ADC_sampling_times", "group___a_d_c__sampling__times.html", "group___a_d_c__sampling__times" ],
    [ "ADC_external_trigger_edge_for_injected_channels_conversion", "group___a_d_c__external__trigger__edge__for__injected__channels__conversion.html", "group___a_d_c__external__trigger__edge__for__injected__channels__conversion" ],
    [ "ADC_extrenal_trigger_sources_for_injected_channels_conversion", "group___a_d_c__extrenal__trigger__sources__for__injected__channels__conversion.html", "group___a_d_c__extrenal__trigger__sources__for__injected__channels__conversion" ],
    [ "ADC_injected_channel_selection", "group___a_d_c__injected__channel__selection.html", "group___a_d_c__injected__channel__selection" ],
    [ "ADC_analog_watchdog_selection", "group___a_d_c__analog__watchdog__selection.html", "group___a_d_c__analog__watchdog__selection" ],
    [ "ADC_interrupts_definition", "group___a_d_c__interrupts__definition.html", "group___a_d_c__interrupts__definition" ],
    [ "ADC_flags_definition", "group___a_d_c__flags__definition.html", "group___a_d_c__flags__definition" ],
    [ "ADC_thresholds", "group___a_d_c__thresholds.html", "group___a_d_c__thresholds" ],
    [ "ADC_injected_offset", "group___a_d_c__injected__offset.html", "group___a_d_c__injected__offset" ],
    [ "ADC_injected_length", "group___a_d_c__injected__length.html", "group___a_d_c__injected__length" ],
    [ "ADC_injected_rank", "group___a_d_c__injected__rank.html", "group___a_d_c__injected__rank" ],
    [ "ADC_regular_length", "group___a_d_c__regular__length.html", "group___a_d_c__regular__length" ],
    [ "ADC_regular_rank", "group___a_d_c__regular__rank.html", "group___a_d_c__regular__rank" ],
    [ "ADC_regular_discontinuous_mode_number", "group___a_d_c__regular__discontinuous__mode__number.html", "group___a_d_c__regular__discontinuous__mode__number" ],
    [ "IS_ADC_ALL_PERIPH", "group___a_d_c___exported___constants.html#gaf5d6bd0153464912e0eaccb1af1aefb2", null ]
];