.TH "ADC_Private_Functions" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Private_Functions \- ADC_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBInitialization and Configuration functions\fP"
.br
.RI "Initialization and Configuration functions\&. "
.ti -1c
.RI "\fBAnalog Watchdog configuration functions\fP"
.br
.RI "Analog Watchdog configuration functions\&. "
.ti -1c
.RI "\fBTemperature Sensor, Vrefint (Voltage Reference internal)\fP"
.br
.RI "Temperature Sensor, Vrefint and VBAT management functions\&. "
.ti -1c
.RI "\fBRegular Channels Configuration functions\fP"
.br
.RI "Regular Channels Configuration functions\&. "
.ti -1c
.RI "\fBRegular Channels DMA Configuration functions\fP"
.br
.RI "Regular Channels DMA Configuration functions\&. "
.ti -1c
.RI "\fBInjected channels Configuration functions\fP"
.br
.RI "Injected channels Configuration functions\&. "
.ti -1c
.RI "\fBInterrupts and flags management functions\fP"
.br
.RI "Interrupts and flags management functions\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
