.TH "ADC_delay_between_2_sampling_phases" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_delay_between_2_sampling_phases \- ADC_delay_between_2_sampling_phases
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_5Cycles\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_6Cycles\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_7Cycles\fP   ((uint32_t)0x00000200)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_8Cycles\fP   ((uint32_t)0x00000300)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_9Cycles\fP   ((uint32_t)0x00000400)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_10Cycles\fP   ((uint32_t)0x00000500)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_11Cycles\fP   ((uint32_t)0x00000600)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_12Cycles\fP   ((uint32_t)0x00000700)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_13Cycles\fP   ((uint32_t)0x00000800)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_14Cycles\fP   ((uint32_t)0x00000900)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_15Cycles\fP   ((uint32_t)0x00000A00)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_16Cycles\fP   ((uint32_t)0x00000B00)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_17Cycles\fP   ((uint32_t)0x00000C00)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_18Cycles\fP   ((uint32_t)0x00000D00)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_19Cycles\fP   ((uint32_t)0x00000E00)"
.br
.ti -1c
.RI "#define \fBADC_TwoSamplingDelay_20Cycles\fP   ((uint32_t)0x00000F00)"
.br
.ti -1c
.RI "#define \fBIS_ADC_SAMPLING_DELAY\fP(DELAY)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_TwoSamplingDelay_10Cycles   ((uint32_t)0x00000500)"

.SS "#define ADC_TwoSamplingDelay_11Cycles   ((uint32_t)0x00000600)"

.SS "#define ADC_TwoSamplingDelay_12Cycles   ((uint32_t)0x00000700)"

.SS "#define ADC_TwoSamplingDelay_13Cycles   ((uint32_t)0x00000800)"

.SS "#define ADC_TwoSamplingDelay_14Cycles   ((uint32_t)0x00000900)"

.SS "#define ADC_TwoSamplingDelay_15Cycles   ((uint32_t)0x00000A00)"

.SS "#define ADC_TwoSamplingDelay_16Cycles   ((uint32_t)0x00000B00)"

.SS "#define ADC_TwoSamplingDelay_17Cycles   ((uint32_t)0x00000C00)"

.SS "#define ADC_TwoSamplingDelay_18Cycles   ((uint32_t)0x00000D00)"

.SS "#define ADC_TwoSamplingDelay_19Cycles   ((uint32_t)0x00000E00)"

.SS "#define ADC_TwoSamplingDelay_20Cycles   ((uint32_t)0x00000F00)"

.SS "#define ADC_TwoSamplingDelay_5Cycles   ((uint32_t)0x00000000)"

.SS "#define ADC_TwoSamplingDelay_6Cycles   ((uint32_t)0x00000100)"

.SS "#define ADC_TwoSamplingDelay_7Cycles   ((uint32_t)0x00000200)"

.SS "#define ADC_TwoSamplingDelay_8Cycles   ((uint32_t)0x00000300)"

.SS "#define ADC_TwoSamplingDelay_9Cycles   ((uint32_t)0x00000400)"

.SS "#define IS_ADC_SAMPLING_DELAY(DELAY)"
\fBValue:\fP.PP
.nf
                                      (((DELAY) == ADC_TwoSamplingDelay_5Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_6Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_7Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_8Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_9Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_10Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_11Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_12Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_13Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_14Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_15Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_16Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_17Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_18Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_19Cycles) || \\
                                      ((DELAY) == ADC_TwoSamplingDelay_20Cycles))
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
