.TH "ADC_regular_discontinuous_mode_number" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_regular_discontinuous_mode_number \- ADC_regular_discontinuous_mode_number
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_ADC_REGULAR_DISC_NUMBER\fP(NUMBER)   (((NUMBER) >= 0x1) && ((NUMBER) <= 0x8))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_ADC_REGULAR_DISC_NUMBER(NUMBER)   (((NUMBER) >= 0x1) && ((NUMBER) <= 0x8))"

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
