.TH "ADC_Exported_Constants" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Exported_Constants \- ADC_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBADC_Common_mode\fP"
.br
.ti -1c
.RI "\fBADC_Prescaler\fP"
.br
.ti -1c
.RI "\fBADC_Direct_memory_access_mode_for_multi_mode\fP"
.br
.ti -1c
.RI "\fBADC_delay_between_2_sampling_phases\fP"
.br
.ti -1c
.RI "\fBADC_resolution\fP"
.br
.ti -1c
.RI "\fBADC_external_trigger_edge_for_regular_channels_conversion\fP"
.br
.ti -1c
.RI "\fBADC_extrenal_trigger_sources_for_regular_channels_conversion\fP"
.br
.ti -1c
.RI "\fBADC_data_align\fP"
.br
.ti -1c
.RI "\fBADC_channels\fP"
.br
.ti -1c
.RI "\fBADC_sampling_times\fP"
.br
.ti -1c
.RI "\fBADC_external_trigger_edge_for_injected_channels_conversion\fP"
.br
.ti -1c
.RI "\fBADC_extrenal_trigger_sources_for_injected_channels_conversion\fP"
.br
.ti -1c
.RI "\fBADC_injected_channel_selection\fP"
.br
.ti -1c
.RI "\fBADC_analog_watchdog_selection\fP"
.br
.ti -1c
.RI "\fBADC_interrupts_definition\fP"
.br
.ti -1c
.RI "\fBADC_flags_definition\fP"
.br
.ti -1c
.RI "\fBADC_thresholds\fP"
.br
.ti -1c
.RI "\fBADC_injected_offset\fP"
.br
.ti -1c
.RI "\fBADC_injected_length\fP"
.br
.ti -1c
.RI "\fBADC_injected_rank\fP"
.br
.ti -1c
.RI "\fBADC_regular_length\fP"
.br
.ti -1c
.RI "\fBADC_regular_rank\fP"
.br
.ti -1c
.RI "\fBADC_regular_discontinuous_mode_number\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_ADC_ALL_PERIPH\fP(PERIPH)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_ADC_ALL_PERIPH(PERIPH)"
\fBValue:\fP.PP
.nf
                                   (((PERIPH) == ADC1) || \\
                                   ((PERIPH) == ADC2) || \\
                                   ((PERIPH) == ADC3))
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
