.TH "ADC_injected_offset" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_injected_offset \- ADC_injected_offset
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_ADC_OFFSET\fP(OFFSET)   ((OFFSET) <= 0xFFF)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_ADC_OFFSET(OFFSET)   ((OFFSET) <= 0xFFF)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
