.TH "drivers Directory Reference" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBadc\&.c\fP"
.br
.ti -1c
.RI "file \fBadc\&.h\fP"
.br
.RI "Internal analogue to digital converter (ADC) controller\&. "
.ti -1c
.RI "file \fBcomparator\&.c\fP"
.br
.ti -1c
.RI "file \fBcomparator\&.h\fP"
.br
.RI "Exposes functions of an internal comparator\&. "
.ti -1c
.RI "file \fBgpio\&.c\fP"
.br
.ti -1c
.RI "file \fBgpio\&.h\fP"
.br
.RI "Implements general purpose I/O\&. "
.ti -1c
.RI "file \fBi2c\&.c\fP"
.br
.ti -1c
.RI "file \fBi2c\&.h\fP"
.br
.RI "Controller for hardware I2C module, configured as a master\&. "
.ti -1c
.RI "file \fBplatform\&.h\fP"
.br
.ti -1c
.RI "file \fBstm32f4xx_adc\&.c\fP"
.br
.RI "This file provides firmware functions to manage the following functionalities of the Analog to Digital Convertor (ADC) peripheral: "
.ti -1c
.RI "file \fBstm32f4xx_adc\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the ADC firmware library\&. "
.ti -1c
.RI "file \fBstm32f4xx_gpio\&.c\fP"
.br
.RI "This file provides firmware functions to manage the following functionalities of the GPIO peripheral: 
.br
 "
.ti -1c
.RI "file \fBstm32f4xx_gpio\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the GPIO firmware library\&. "
.ti -1c
.RI "file \fBstm32f4xx_i2c\&.c\fP"
.br
.RI "This file provides firmware functions to manage the following functionalities of the Inter-integrated circuit (I2C) "
.ti -1c
.RI "file \fBstm32f4xx_i2c\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the I2C firmware library\&. "
.ti -1c
.RI "file \fBstm32f4xx_rcc\&.c\fP"
.br
.RI "This file provides firmware functions to manage the following functionalities of the Reset and clock control (RCC) peripheral: "
.ti -1c
.RI "file \fBstm32f4xx_rcc\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the RCC firmware library\&. "
.ti -1c
.RI "file \fBstm32f4xx_usart\&.c\fP"
.br
.RI "This file provides firmware functions to manage the following functionalities of the Universal synchronous asynchronous receiver transmitter (USART): 
.br
 "
.ti -1c
.RI "file \fBstm32f4xx_usart\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the USART firmware library\&. "
.ti -1c
.RI "file \fBtimer\&.c\fP"
.br
.ti -1c
.RI "file \fBtimer\&.h\fP"
.br
.RI "Controller for a hardware timer module\&. "
.ti -1c
.RI "file \fBuart\&.c\fP"
.br
.ti -1c
.RI "file \fBuart\&.h\fP"
.br
.RI "Controller for a hardware UART module\&. "
.in -1c
