.TH "drivers/comparator.c" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drivers/comparator.c
.SH SYNOPSIS
.br
.PP
\fC#include <platform\&.h>\fP
.br
\fC#include <comparator\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcomparator_init\fP (void)"
.br
.RI "Initializes the internal comparator\&. "
.ti -1c
.RI "int \fBcomparator_read\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void comparator_init (void)"

.PP
Initializes the internal comparator\&. 
.SS "int comparator_read (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
