.TH "GPIO_Pin_sources" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Pin_sources \- GPIO_Pin_sources
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGPIO_PinSource0\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource1\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource2\fP   ((uint8_t)0x02)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource3\fP   ((uint8_t)0x03)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource4\fP   ((uint8_t)0x04)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource5\fP   ((uint8_t)0x05)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource6\fP   ((uint8_t)0x06)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource7\fP   ((uint8_t)0x07)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource8\fP   ((uint8_t)0x08)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource9\fP   ((uint8_t)0x09)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource10\fP   ((uint8_t)0x0A)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource11\fP   ((uint8_t)0x0B)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource12\fP   ((uint8_t)0x0C)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource13\fP   ((uint8_t)0x0D)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource14\fP   ((uint8_t)0x0E)"
.br
.ti -1c
.RI "#define \fBGPIO_PinSource15\fP   ((uint8_t)0x0F)"
.br
.ti -1c
.RI "#define \fBIS_GPIO_PIN_SOURCE\fP(PINSOURCE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define GPIO_PinSource0   ((uint8_t)0x00)"

.SS "#define GPIO_PinSource1   ((uint8_t)0x01)"

.SS "#define GPIO_PinSource10   ((uint8_t)0x0A)"

.SS "#define GPIO_PinSource11   ((uint8_t)0x0B)"

.SS "#define GPIO_PinSource12   ((uint8_t)0x0C)"

.SS "#define GPIO_PinSource13   ((uint8_t)0x0D)"

.SS "#define GPIO_PinSource14   ((uint8_t)0x0E)"

.SS "#define GPIO_PinSource15   ((uint8_t)0x0F)"

.SS "#define GPIO_PinSource2   ((uint8_t)0x02)"

.SS "#define GPIO_PinSource3   ((uint8_t)0x03)"

.SS "#define GPIO_PinSource4   ((uint8_t)0x04)"

.SS "#define GPIO_PinSource5   ((uint8_t)0x05)"

.SS "#define GPIO_PinSource6   ((uint8_t)0x06)"

.SS "#define GPIO_PinSource7   ((uint8_t)0x07)"

.SS "#define GPIO_PinSource8   ((uint8_t)0x08)"

.SS "#define GPIO_PinSource9   ((uint8_t)0x09)"

.SS "#define IS_GPIO_PIN_SOURCE(PINSOURCE)"
\fBValue:\fP.PP
.nf
                                       (((PINSOURCE) == GPIO_PinSource0) || \\
                                       ((PINSOURCE) == GPIO_PinSource1) || \\
                                       ((PINSOURCE) == GPIO_PinSource2) || \\
                                       ((PINSOURCE) == GPIO_PinSource3) || \\
                                       ((PINSOURCE) == GPIO_PinSource4) || \\
                                       ((PINSOURCE) == GPIO_PinSource5) || \\
                                       ((PINSOURCE) == GPIO_PinSource6) || \\
                                       ((PINSOURCE) == GPIO_PinSource7) || \\
                                       ((PINSOURCE) == GPIO_PinSource8) || \\
                                       ((PINSOURCE) == GPIO_PinSource9) || \\
                                       ((PINSOURCE) == GPIO_PinSource10) || \\
                                       ((PINSOURCE) == GPIO_PinSource11) || \\
                                       ((PINSOURCE) == GPIO_PinSource12) || \\
                                       ((PINSOURCE) == GPIO_PinSource13) || \\
                                       ((PINSOURCE) == GPIO_PinSource14) || \\
                                       ((PINSOURCE) == GPIO_PinSource15))
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
