.TH "I2C_Private_Functions" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Private_Functions \- I2C_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBInitialization and Configuration functions\fP"
.br
.RI "Initialization and Configuration functions\&. "
.ti -1c
.RI "\fBData transfers functions\fP"
.br
.RI "Data transfers functions\&. "
.ti -1c
.RI "\fBPEC management functions\fP"
.br
.RI "PEC management functions\&. "
.ti -1c
.RI "\fBDMA transfers management functions\fP"
.br
.RI "DMA transfers management functions\&. "
.ti -1c
.RI "\fBInterrupts events and flags management functions\fP"
.br
.RI "Interrupts, events and flags management functions\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
