.TH "I2C_Exported_Constants" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Exported_Constants \- I2C_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBI2C_mode\fP"
.br
.ti -1c
.RI "\fBI2C_duty_cycle_in_fast_mode\fP"
.br
.ti -1c
.RI "\fBI2C_acknowledgement\fP"
.br
.ti -1c
.RI "\fBI2C_transfer_direction\fP"
.br
.ti -1c
.RI "\fBI2C_acknowledged_address\fP"
.br
.ti -1c
.RI "\fBI2C_registers\fP"
.br
.ti -1c
.RI "\fBI2C_NACK_position\fP"
.br
.ti -1c
.RI "\fBI2C_SMBus_alert_pin_level\fP"
.br
.ti -1c
.RI "\fBI2C_PEC_position\fP"
.br
.ti -1c
.RI "\fBI2C_interrupts_definition\fP"
.br
.ti -1c
.RI "\fBI2C_flags_definition\fP"
.br
.ti -1c
.RI "\fBI2C_Events\fP"
.br
.ti -1c
.RI "\fBI2C_own_address1\fP"
.br
.ti -1c
.RI "\fBI2C_clock_speed\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_I2C_ALL_PERIPH\fP(PERIPH)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_I2C_ALL_PERIPH(PERIPH)"
\fBValue:\fP.PP
.nf
                                   (((PERIPH) == I2C1) || \\
                                   ((PERIPH) == I2C2) || \\
                                   ((PERIPH) == I2C3))
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
