.TH "I2C_clock_speed" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_clock_speed \- I2C_clock_speed
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_I2C_CLOCK_SPEED\fP(SPEED)   (((SPEED) >= 0x1) && ((SPEED) <= 400000))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_I2C_CLOCK_SPEED(SPEED)   (((SPEED) >= 0x1) && ((SPEED) <= 400000))"

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
