.TH "RCC_AHB2_Peripherals" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_AHB2_Peripherals \- RCC_AHB2_Peripherals
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_AHB2Periph_DCMI\fP   ((uint32_t)0x00000001)"
.br
.ti -1c
.RI "#define \fBRCC_AHB2Periph_CRYP\fP   ((uint32_t)0x00000010)"
.br
.ti -1c
.RI "#define \fBRCC_AHB2Periph_HASH\fP   ((uint32_t)0x00000020)"
.br
.ti -1c
.RI "#define \fBRCC_AHB2Periph_RNG\fP   ((uint32_t)0x00000040)"
.br
.ti -1c
.RI "#define \fBRCC_AHB2Periph_OTG_FS\fP   ((uint32_t)0x00000080)"
.br
.ti -1c
.RI "#define \fBIS_RCC_AHB2_PERIPH\fP(PERIPH)   ((((PERIPH) & 0xFFFFFF0E) == 0x00) && ((PERIPH) != 0x00))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_RCC_AHB2_PERIPH(PERIPH)   ((((PERIPH) & 0xFFFFFF0E) == 0x00) && ((PERIPH) != 0x00))"

.SS "#define RCC_AHB2Periph_CRYP   ((uint32_t)0x00000010)"

.SS "#define RCC_AHB2Periph_DCMI   ((uint32_t)0x00000001)"

.SS "#define RCC_AHB2Periph_HASH   ((uint32_t)0x00000020)"

.SS "#define RCC_AHB2Periph_OTG_FS   ((uint32_t)0x00000080)"

.SS "#define RCC_AHB2Periph_RNG   ((uint32_t)0x00000040)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
