.TH "RCC_I2S_Clock_Source" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_I2S_Clock_Source \- RCC_I2S_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_I2S2CLKSource_PLLI2S\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBRCC_I2S2CLKSource_Ext\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBIS_RCC_I2SCLK_SOURCE\fP(SOURCE)   (((SOURCE) == \fBRCC_I2S2CLKSource_PLLI2S\fP) || ((SOURCE) == \fBRCC_I2S2CLKSource_Ext\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_RCC_I2SCLK_SOURCE(SOURCE)   (((SOURCE) == \fBRCC_I2S2CLKSource_PLLI2S\fP) || ((SOURCE) == \fBRCC_I2S2CLKSource_Ext\fP))"

.SS "#define RCC_I2S2CLKSource_Ext   ((uint8_t)0x01)"

.SS "#define RCC_I2S2CLKSource_PLLI2S   ((uint8_t)0x00)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
