.TH "RCC_APB2_Peripherals" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_APB2_Peripherals \- RCC_APB2_Peripherals
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM1\fP   ((uint32_t)0x00000001)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM8\fP   ((uint32_t)0x00000002)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_USART1\fP   ((uint32_t)0x00000010)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_USART6\fP   ((uint32_t)0x00000020)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_ADC\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_ADC1\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_ADC2\fP   ((uint32_t)0x00000200)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_ADC3\fP   ((uint32_t)0x00000400)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_SDIO\fP   ((uint32_t)0x00000800)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_SPI1\fP   ((uint32_t)0x00001000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_SYSCFG\fP   ((uint32_t)0x00004000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM9\fP   ((uint32_t)0x00010000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM10\fP   ((uint32_t)0x00020000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM11\fP   ((uint32_t)0x00040000)"
.br
.ti -1c
.RI "#define \fBIS_RCC_APB2_PERIPH\fP(PERIPH)   ((((PERIPH) & 0xFFF8A0CC) == 0x00) && ((PERIPH) != 0x00))"
.br
.ti -1c
.RI "#define \fBIS_RCC_APB2_RESET_PERIPH\fP(PERIPH)   ((((PERIPH) & 0xFFF8A6CC) == 0x00) && ((PERIPH) != 0x00))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_RCC_APB2_PERIPH(PERIPH)   ((((PERIPH) & 0xFFF8A0CC) == 0x00) && ((PERIPH) != 0x00))"

.SS "#define IS_RCC_APB2_RESET_PERIPH(PERIPH)   ((((PERIPH) & 0xFFF8A6CC) == 0x00) && ((PERIPH) != 0x00))"

.SS "#define RCC_APB2Periph_ADC   ((uint32_t)0x00000100)"

.SS "#define RCC_APB2Periph_ADC1   ((uint32_t)0x00000100)"

.SS "#define RCC_APB2Periph_ADC2   ((uint32_t)0x00000200)"

.SS "#define RCC_APB2Periph_ADC3   ((uint32_t)0x00000400)"

.SS "#define RCC_APB2Periph_SDIO   ((uint32_t)0x00000800)"

.SS "#define RCC_APB2Periph_SPI1   ((uint32_t)0x00001000)"

.SS "#define RCC_APB2Periph_SYSCFG   ((uint32_t)0x00004000)"

.SS "#define RCC_APB2Periph_TIM1   ((uint32_t)0x00000001)"

.SS "#define RCC_APB2Periph_TIM10   ((uint32_t)0x00020000)"

.SS "#define RCC_APB2Periph_TIM11   ((uint32_t)0x00040000)"

.SS "#define RCC_APB2Periph_TIM8   ((uint32_t)0x00000002)"

.SS "#define RCC_APB2Periph_TIM9   ((uint32_t)0x00010000)"

.SS "#define RCC_APB2Periph_USART1   ((uint32_t)0x00000010)"

.SS "#define RCC_APB2Periph_USART6   ((uint32_t)0x00000020)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
