.TH "RCC_ClocksTypeDef" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_ClocksTypeDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_rcc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBSYSCLK_Frequency\fP"
.br
.ti -1c
.RI "uint32_t \fBHCLK_Frequency\fP"
.br
.ti -1c
.RI "uint32_t \fBPCLK1_Frequency\fP"
.br
.ti -1c
.RI "uint32_t \fBPCLK2_Frequency\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t HCLK_Frequency"
HCLK clock frequency expressed in Hz 
.SS "uint32_t PCLK1_Frequency"
PCLK1 clock frequency expressed in Hz 
.SS "uint32_t PCLK2_Frequency"
PCLK2 clock frequency expressed in Hz 
.SS "uint32_t SYSCLK_Frequency"
SYSCLK clock frequency expressed in Hz 

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
