.TH "RTE/_Target_1/RTE_Components.h" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTE/_Target_1/RTE_Components.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCMSIS_device_header\fP   'stm32f4xx\&.h'"
.br
.ti -1c
.RI "#define \fBRTE_DEVICE_STARTUP_STM32F4XX\fP   /* Device Startup for STM32F4 */"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CMSIS_device_header   'stm32f4xx\&.h'"

.SS "#define RTE_DEVICE_STARTUP_STM32F4XX   /* Device Startup for STM32F4 */"

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
