.TH "STM32F4xx_StdPeriph_Driver" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F4xx_StdPeriph_Driver \- STM32F4xx_StdPeriph_Driver
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBADC\fP"
.br
.RI "ADC driver modules\&. "
.ti -1c
.RI "\fBGPIO\fP"
.br
.RI "GPIO driver modules\&. "
.ti -1c
.RI "\fBI2C\fP"
.br
.RI "I2C driver modules\&. "
.ti -1c
.RI "\fBRCC\fP"
.br
.RI "RCC driver modules\&. "
.ti -1c
.RI "\fBUSART\fP"
.br
.RI "USART driver modules\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
