.TH "STM32F4xx_System_Private_Includes" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F4xx_System_Private_Includes \- STM32F4xx_System_Private_Includes
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSE_VALUE\fP   ((uint32_t)25000000)"
.br
.ti -1c
.RI "#define \fBHSI_VALUE\fP   ((uint32_t)16000000)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HSE_VALUE   ((uint32_t)25000000)"
Default value of the External oscillator in Hz 
.SS "#define HSI_VALUE   ((uint32_t)16000000)"
Value of the Internal oscillator in Hz 
.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
