.TH "STM32F4xx_System_Private_FunctionPrototypes" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F4xx_System_Private_FunctionPrototypes \- STM32F4xx_System_Private_FunctionPrototypes
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
