.TH "USART_Hardware_Flow_Control" 3 "Version 0.1.-" "Square Root Approximation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Hardware_Flow_Control \- USART_Hardware_Flow_Control
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSART_HardwareFlowControl_None\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBUSART_HardwareFlowControl_RTS\fP   ((uint16_t)0x0100)"
.br
.ti -1c
.RI "#define \fBUSART_HardwareFlowControl_CTS\fP   ((uint16_t)0x0200)"
.br
.ti -1c
.RI "#define \fBUSART_HardwareFlowControl_RTS_CTS\fP   ((uint16_t)0x0300)"
.br
.ti -1c
.RI "#define \fBIS_USART_HARDWARE_FLOW_CONTROL\fP(CONTROL)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_USART_HARDWARE_FLOW_CONTROL(CONTROL)"
\fBValue:\fP.PP
.nf
                              (((CONTROL) == USART_HardwareFlowControl_None) || \\
                               ((CONTROL) == USART_HardwareFlowControl_RTS) || \\
                               ((CONTROL) == USART_HardwareFlowControl_CTS) || \\
                               ((CONTROL) == USART_HardwareFlowControl_RTS_CTS))
.fi

.SS "#define USART_HardwareFlowControl_CTS   ((uint16_t)0x0200)"

.SS "#define USART_HardwareFlowControl_None   ((uint16_t)0x0000)"

.SS "#define USART_HardwareFlowControl_RTS   ((uint16_t)0x0100)"

.SS "#define USART_HardwareFlowControl_RTS_CTS   ((uint16_t)0x0300)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Square Root Approximation from the source code\&.
